eplPlugins:
  brickpiPlugin:
    pythonFile: src/python/brickpi-epl-plugin.py
    class: BrickPiPlugin
    pythonPath:
      - /home/pi/Dexter/BrickPi3/Software/Python
      - /home/pi/.local/lib/python3.7/site-packages
correlator:
  pythonSupport: true
  initialization:
    list:
      - ${APAMA_HOME}/monitors/AnyExtractor.mon
      - src/epl/EventDefs.mon
      - src/epl/BrickPi.mon
